# Generated by Django 5.2 on 2025-04-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproblem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='skill_coding.codingtrack'),
        ),
    ]
