# Generated by Django 5.2 on 2025-04-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_users', '0005_coursematerial_scheduledevent_studentprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
    ]
