# Generated by Django 5.2 on 2025-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_lms', '0002_course_created_at_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
